-- Questão 1: Valor total das vendas e fretes por produto e ordem de venda

SELECT
		PROD.PRODUTO
,		FACA.CUPOMID AS ORDEM_VENDA
,		CONCAT('R$ ', FORMAT(SUM((FADE.QUANTIDADE * REPLACE(FADE.VALOR, ',', '.')) - FADE.DESCONTO), 2)) AS TOTAL_VENDA
, 		CONCAT('R$ ', FORMAT(REPLACE(FACA.Valorfrete, ',', '.'), 2)) AS TOTAL_FRETE

FROM	LOJA.FATOCABECALHO AS FACA 

INNER
JOIN	LOJA.FATODETALHES AS FADE 
ON 		FACA.CUPOMID = FADE.CUPOMID

INNER
JOIN	LOJA.PRODUTOS AS PROD
ON 		FADE.PRODUTOID = PROD.PRODUTOID

GROUP
BY		PROD.PRODUTO
	,	FACA.CUPOMID

ORDER 
BY 		PROD.PRODUTO
, 		FACA.CUPOMID;

-- Questão 2: Valor de venda por tipo de produto
SELECT
		CATE.CATEGORIA AS CATEGORIA
,		CONCAT('R$ ', FORMAT(SUM((FADE.QUANTIDADE * REPLACE(FADE.VALOR, ',', '.')) - FADE.DESCONTO), 2)) AS TOTAL_VENDA

FROM	LOJA.FATOCABECALHO AS FACA

INNER
JOIN	LOJA.FATODETALHES AS FADE
ON 		FACA.CUPOMID = FADE.CUPOMID

INNER
JOIN	LOJA.PRODUTOS AS PROD
ON 		FADE.PRODUTOID = PROD.PRODUTOID

INNER
JOIN	LOJA.CATEGORIA AS CATE
ON 		PROD.CATEGORIAID = CATE.CATEGORIAID

GROUP
BY		CATE.CATEGORIA

ORDER 
BY		CATE.CATEGORIA;

-- Questão 3: Quantidade e valor das vendas por dia mês, ano
SELECT 
		FACA.DATA
,		SUM(FADE.QUANTIDADE) AS QUANTIDADE
,		CONCAT('R$ ', FORMAT(SUM((FADE.QUANTIDADE * REPLACE(FADE.VALOR, ',', '.')) - FADE.DESCONTO), 2)) AS TOTAL_VENDA

FROM	LOJA.FATOCABECALHO AS FACA

INNER
JOIN	LOJA.FATODETALHES AS FADE
ON 		FACA.CUPOMID = FADE.CUPOMID

GROUP
BY		FACA.DATA

ORDER
BY		STR_TO_DATE(FACA.DATA, '%d/%m/%Y') DESC;

-- Questão 4: Lucro dos meses
SELECT
		SUBSTRING(FACA.DATA, 4, 2) AS MES
,		CONCAT('R$ ', FORMAT(SUM(REPLACE(FADE.VALORLIQUIDO, ',', '.') * FADE.QUANTIDADE), 2)) AS LUCRO

FROM	FATOCABECALHO AS FACA

INNER
JOIN 	FATODETALHES AS FADE
ON		FACA.CUPOMID = FADE.CUPOMID

GROUP 
BY 		SUBSTRING(FACA.DATA, 4, 2)

ORDER 
BY		SUBSTRING(FACA.DATA, 4, 2);

-- Questão 5: Venda por produto
SELECT
		PROD.PRODUTO AS PRODUTO
,		CONCAT('R$ ', FORMAT(SUM((FADE.QUANTIDADE * REPLACE(FADE.VALOR, ',', '.')) - FADE.DESCONTO), 2)) AS TOTAL_VENDA

FROM	LOJA.FATOCABECALHO AS FACA

INNER
JOIN	LOJA.FATODETALHES AS FADE
ON 		FACA.CUPOMID = FADE.CUPOMID

INNER
JOIN	LOJA.PRODUTOS AS PROD
ON 		FADE.PRODUTOID = PROD.PRODUTOID

GROUP
BY		PROD.PRODUTO

ORDER 
BY		PROD.PRODUTO;



/********************************************************
Questão 6: Venda por cliente, cidade do cliente e estado

Nesta query não temos a informação do estado, pois não se encontra na base de dados fornecida pelo desafio.
*********************************************************/
SELECT 
		CLIE.NOMECONTATO
,		CLIE.CIDADE
,		CONCAT('R$ ', FORMAT(SUM((FADE.QUANTIDADE * REPLACE(FADE.VALOR, ',', '.')) - FADE.DESCONTO), 2)) AS VENDA
        
FROM	LOJA.FATOCABECALHO AS FACA

INNER
JOIN	LOJA.FATODETALHES AS FADE
ON 		FACA.CUPOMID = FADE.CUPOMID

INNER
JOIN	CLIENTES AS CLIE
ON		FACA.CLIENTEID = CLIE.CLIENTEID

GROUP
BY		CLIE.NOMECONTATO
,		CLIE.CIDADE

ORDER
BY		CLIE.NOMECONTATO
,		CLIE.CIDADE;

-- Questão 7: Média de produtos vendidos
SELECT 
		PROD.PRODUTO
,		AVG(FADE.QUANTIDADE) AS MEDIA
        
FROM	FATOCABECALHO AS FACA

INNER
JOIN	FATODETALHES AS FADE
ON 		FACA.CUPOMID = FADE.CUPOMID

INNER
JOIN	PRODUTOS AS PROD
ON 		FADE.PRODUTOID = PROD.PRODUTOID

GROUP
BY 		PROD.PRODUTO

ORDER
BY		PROD.PRODUTO;

-- Questão 8: Média de compras que um cliente faz 
SELECT 
		SUM(FADE.QUANTIDADE) / COUNT(FACA.CLIENTEID) AS MEDIA_COMPRA

FROM	FATOCABECALHO AS FACA

INNER
JOIN	FATODETALHES AS FADE
ON 		FACA.CUPOMID = FADE.CUPOMID;
